<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $this->call('ModuleTableSeeder');

      $this->command->info('Modules table seeded!');
    }
}

class ModuleTableSeeder extends Seeder {

    public function run()
    {
        DB::table('modules')->delete();
        DB::table('modules')->insert([
              [
               'id' => 'IOPR1',
               'name' => 'Inleiding Object Georienteerd programmeren 1',
               'year' => 1,
               'semester' => 1,
               'ects' => 4,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IARCH',
               'name' => 'IT architectuur',
               'year' => 1,
               'semester' => 1,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IIBPM',
               'name' => 'inleiding informatiemanagement/BPM',
               'year' => 1,
               'semester' => 1,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IHBO',
               'name' => 'fundamentele HBO - (I) vaardigheden',
               'year' => 1,
               'semester' => 1,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IWDR',
               'name' => 'webdesign & realisatie',
               'year' => 1,
               'semester' => 2,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IRDB',
               'name' => 'relationele databases',
               'year' => 1,
               'semester' => 2,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IIBUI',
               'name' => 'inleiding business intelligence',
               'year' => 1,
               'semester' => 2,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IPODM',
               'name' => 'praktische opdracht business data management',
               'year' => 1,
               'semester' => 2,
               'ects' => 2,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IPOMEDT',
               'name' => 'praktische opdracht mediatechnologie',
               'year' => 1,
               'semester' => 2,
               'ects' => 2,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'INET',
               'name' => 'IT netwerkstructuren',
               'year' => 1,
               'semester' => 12,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IMUML',
               'name' => 'modelleren in UML',
               'year' => 1,
               'semester' => 3,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IOPR2',
               'name' => 'objectgeoriënteerd programmeren 2',
               'year' => 1,
               'semester' => 3,
               'ects' => 4,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IFIT',
               'name' => 'inleiding forensische ICT',
               'year' => 1,
               'semester' => 3,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IPOFIT',
               'name' => 'praktische opdracht forensisch ICT',
               'year' => 1,
               'semester' => 3,
               'ects' => 2,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IPOSE',
               'name' => 'praktische opdracht software engineering',
               'year' => 1,
               'semester' => 3,
               'ects' => 2,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'IPROV',
               'name' => 'ICT projectvaardigheden',
               'year' => 1,
               'semester' => 234,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'ICOMMP',
               'name' => 'communicatie 1',
               'year' => 1,
               'semester' => 234,
               'ects' => 3,
               'soort' => 'hoofdvak',
             ],
             [
               'id' => 'ISLP',
               'name' => 'studieloopbaanbegeleiding',
               'year' => 1,
               'semester' => 1234,
               'ects' => 1,
               'soort' => 'hoofdvak',
             ],
             [
                'id' => 'IIPBDAM',
                'name' => 'project inleiding BDaM',
                'year' => 1,
                'semester' => 4,
                'ects' => 10,
                'soort' => 'keuzevak',
             ],
            [
                'id' => 'IIPFIT',
                'name' => 'project inleiding FICT',
                'year' => 1,
                'semester' => 4,
                'ects' => 10,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IIPMEDT',
                'name' => 'project inleiding MedT',
                'year' => 1,
                'semester' => 4,
                'ects' => 10,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IIPSEN',
                'name' => 'project inleiding SE',
                'year' => 1,
                'semester' => 4,
                'ects' => 10,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IRDBMS',
                'name' => 'relationele database systemen',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IPMEDT2',
                'name' => 'project mediatechnologie 2',
                'year' => 2,
                'semester' => 1,
                'ects' => 6,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTD1',
                'name' => 'mediatechnologie design 1',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ICOMMH',
                'name' => 'communicatie hoofdfase',
                'year' => 2,
                'semester' => 123,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ISLH',
                'name' => 'studieloopbaanbegeleiding hoofdfase',
                'year' => 234,
                'semester' => 1234,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ISCRIPT',
                'name' => 'scripting',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IPMEDT3',
                'name' => 'project mediatechnologie 3',
                'year' => 2,
                'semester' => 2,
                'ects' => 6,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTUE',
                'name' => 'usability design',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IQUA',
                'name' => 'kwaliteit in de IT',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IPMEDT5',
                'name' => 'project mediatechnologie 5',
                'year' => 2,
                'semester' => 3,
                'ects' => 6,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTCM',
                'name' => 'mediatechnologie creative marketing',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IETH',
                'name' => 'ethiek',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IPMEDT4',
                'name' => 'project mediatechnologie 4',
                'year' => 2,
                'semester' => 4,
                'ects' => 6,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTPMD',
                'name' => 'programming for mobile devices',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IITORG',
                'name' => 'inleiding organisatiekunde',
                'year' => 34,
                'semester' => 103,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ISEC',
                'name' => 'IT security',
                'year' => 34,
                'semester' => 204,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IPMEDTH',
                'name' => 'hoofdfase-project mediatechnologie',
                'year' => 34,
                'semester' => 12034,
                'ects' => 9,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTHE1',
                'name' => 'mediatechnologie hardware engineering 1',
                'year' => 34,
                'semester' => 103,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTHMI',
                'name' => 'human-machine-interaction',
                'year' => 34,
                'semester' => 103,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IMTUX',
                'name' => 'user experience',
                'year' => 34,
                'semester' => 204,
                'ects' => 3,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IWLS',
                'name' => 'stage',
                'year' => 34,
                'semester' => 12034,
                'ects' => 30,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'IWlA',
                'name' => 'afstuderen',
                'year' => 34,
                'semester' => 12034,
                'ects' => 30,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ISENMT',
                'name' => 'sensortechnologie en media',
                'year' => 34,
                'semester' => 12034,
                'ects' => 30,
                'soort' => 'hoofdvak',
            ],
            [
                'id' => 'ISTAT',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ITRAPP',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 102,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IBROZ',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ICOMAS',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 102,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IDEPA',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ISDELI',
                'name' => 'statastiek',
                'year' => 2,
                'semester' => 1,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IWIS',
                'name' => 'wiskunde',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKOPR',
                'name' => 'objectgeoriënteerd programmeren hoofdfase',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKPMD',
                'name' => 'programming for mobile devices',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ISDEMA',
                'name' => 'IT servicemanagement demand',
                'year' => 2,
                'semester' => 2,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IITPS',
                'name' => 'IT psychologie',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IBK5',
                'name' => 'opzetten eigen IT-bedrijf',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IFP2',
                'name' => 'projectmanagement PRINCE2',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKLO',
                'name' => 'logica',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ITREWA',
                'name' => 'trendwatching',
                'year' => 2,
                'semester' => 3,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'ILNUX1',
                'name' => 'linux 1',
                'year' => 2,
                'semester' => 34,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKUE',
                'name' => 'usability engineering',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKEMA',
                'name' => 'kennismanagement',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKDAM',
                'name' => 'datamanagement',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IKCP',
                'name' => 'concepten in programmeertalen',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
            [
                'id' => 'IHS',
                'name' => 'heterogene systemen',
                'year' => 2,
                'semester' => 4,
                'ects' => 3,
                'soort' => 'keuzevak',
            ],
        ]);
    }

}
